default: &default
  adapter: postgresql

development:
  <<: *default
  database: timeclok_development

test:
  <<: *default
  database: timeclok_test

production:
  <<: *default
  database: timeclok_production
